name: muvision
description: Una aplicación para ayudar a personas con discapacidad visual en el museo.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2

  barcode_scan: ^0.0.4
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.5.9
  material_design_icons_flutter: 3.2.4096

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  image_path: "lib/assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/
